# Dockerfile for Rust development environment
# See https://github.com/devcontainers/images/tree/main/src/rust
FROM mcr.microsoft.com/devcontainers/rust:2-1-trixie

# [Optional] Install additional OS packages if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-additional-packages>